# Generated by Django 5.1.1 on 2024-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
